dashboard/urls.py
from . import views
from django.urls import path

app_name = 'dashboard'

urlpatterns = [

    #/dashboard/
    path('', views.index, name='index'),
    path('order', views.order, name='order'),
    path('order_add', views.order_add, name='order_add'),
    path('order_submit', views.order_submit, name='order_submit'),
    path('order_detail/<str:order_date>', views.order_detail, name='order_detail'),
    path('shop', views.shop, name='shop'),
    path('shop_add', views.shop_add, name='shop_add'),
    path('shop_submit', views.shop_submit, name='shop_submit'),
    path('shop_edit/<int:store_pk>/',views.shop_edit, name='shop_edit'),
    path('shop_detail/<int:store_pk>/',views.shop_detail, name='shop_detail'),
    path('shop_delete/<int:store_pk>/',views.shop_delete, name='shop_delete'),
    path('shop_search', views.shop_search, name='shop_search'),
    path('user', views.user, name='user'),
    path('user_edit', views.user_edit, name='user_edit'),
    path('user_submit', views.user_submit, name='user_submit'),
    path('resource', views.resource, name='resource'),
    path('truck_add', views.truck_add, name='truck_add'),
    path('truck_submit', views.truck_submit, name='truck_submit'),
    path('truck_edit/<int:truck_pk>/',views.truck_edit, name='truck_edit'),
    path('truck_delete/<int:truck_pk>/',views.truck_delete, name='truck_delete'),
    path('facility_add', views.facility_add, name='facility_add'),
    path('facility_edit/<int:facility_pk>/',views.facility_edit, name='facility_edit'),
    path('facility_delete/<int:facility_pk>/',views.facility_delete, name='facility_delete'),
    path('facility_submit', views.facility_submit, name='facility_submit'),
    path('item_add', views.item_add, name='item_add'),
    path('item_edit/<int:item_pk>/',views.item_edit, name='item_edit'),
    path('item_detail/<int:item_pk>/',views.item_detail, name='item_detail'),
    path('item_submit', views.item_submit, name='item_submit'),
    path('item_delete/<int:item_pk>/',views.item_delete, name='item_delete'),
    path('item', views.item, name='item'),
    path('register',views.register,name="register"),
    path('register_submt',views.register_submit,name="register_submit"),
    path('login',views.login_page,name="login"),
    path('login_submit',views.login_submit,name="login_submit"),
    path('logout',views.logout_view,name="logout"),
    #path('register', views.UserFormView.as_view(), name='register')
]

lastmile/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls'))
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Order_sku(models.Model):
    shop_Id = models.PositiveIntegerField()
    sku = models.CharField(max_length=20)

    def __str__(self):
        return str(self.shop_Id)+' '+self.sku


class Distributor(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=100)
    address1 = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Retailer(models.Model):
    shop_id = models.CharField(max_length=100)
    distributor = models.ForeignKey(Distributor, on_delete = models.CASCADE)
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=100)
    address1 = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return self.name

    class Meta:
        unique_together = (('shop_id', 'distributor'),)

class Facility(models.Model):
    name = models.CharField(max_length=100)
    facility_id = models.CharField(max_length=100)
    number = models.CharField(max_length=100)
    address1 = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    distributor = models.ForeignKey(Distributor, on_delete = models.CASCADE)
    latitude = models.FloatField()
    longitude = models.FloatField()

class Van(models.Model):
    distributor = models.ForeignKey(Distributor, on_delete = models.CASCADE)
    van_id = models.CharField(max_length=100)
    capacity_vol = models.FloatField()
    capacity_weight = models.FloatField()
    rate_per_mile = models.FloatField()
    fixed_cost = models.FloatField()
    speed = models.FloatField()

class Item(models.Model):
    distributor = models.ForeignKey(Distributor, on_delete = models.CASCADE)
    item_id = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    weight = models.FloatField()
    volume = models.FloatField()


class Order_item(models.Model):
    retailer = models.ForeignKey(Retailer, on_delete = models.CASCADE)
    order_id = models.CharField(max_length=100)
    date =  models.DateField()
    item = models.ForeignKey(Item, on_delete = models.CASCADE)
    quantity = models.PositiveIntegerField()

class Order_summary(models.Model):
    retailer = models.ForeignKey(Retailer, on_delete = models.CASCADE)
    order_id =  models.CharField(max_length=100)
    date =  models.DateField()
    quantity_sum = models.PositiveIntegerField()
    weight_sum = models.FloatField()
    vol_sum = models.FloatField()
    latitude = models.FloatField()
    longitude = models.FloatField()

class Route(models.Model):
    date =  models.DateField()
    sequence = models.PositiveIntegerField()
    order_id =  models.CharField(max_length=100)
    sum_unique_item = models.PositiveIntegerField()
    sum_quantity = models.PositiveIntegerField()
    van = models.ForeignKey(Van, on_delete = models.CASCADE)


class Pick(models.Model):
    date =  models.DateField()
    route = models.ForeignKey(Route, on_delete = models.CASCADE)
    order_id =  models.CharField(max_length=100)
    item = models.ForeignKey(Item, on_delete = models.CASCADE)
    item_quantity = models.PositiveIntegerField()
    van = models.ForeignKey(Van, on_delete = models.CASCADE)

class User_assignment(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    distributor = models.ForeignKey(Distributor, on_delete = models.CASCADE)

dashboard/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'password']

dashboard/views.py
from django.http import Http404,HttpResponse
from django.shortcuts import render, get_object_or_404,redirect
from .models import Order_sku
from .models import Distributor, Retailer, Item, Order_item, Order_summary,Van, Facility, User_assignment
from django.db.models import Count,Sum,F,FloatField
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .forms import UserForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

import random


# Create your views here.
class UserFormView(View):
    form_class = UserForm
    template_name = 'registration_form.html'

    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name, {'form':form})

    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password)
            user.save()

            user = authenticate(username=username,password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect("dashboard:user")

        return render(request,self.template_name, {'form':form})





def register(request):
    return render(request,'register.html')

def register_submit(request):

     if request.method == "GET":
         return redirect("dashboard:register")


     username = request.POST['username']
     password = request.POST['password']


     user = User()
     user.username = username
     user.set_password(password)
     user.save()

     name = request.POST['dist_name']
     number = request.POST['number']
     address1 = request.POST['address1']
     address2 = request.POST['address2']
     city = request.POST['city']
     state = request.POST['state']
     dbr = Distributor(name=name, number=number, address1=address1, city=city, state=state)
     dbr.save()

     user_assign = User_assignment(user = user, distributor=dbr)
     user_assign.save()

     user = authenticate(username=username,password=password)
     login(request,user)

     return redirect("dashboard:user")


def login_page(request):
    return render(request, 'login.html')

def login_submit(request):

    if request.method == "GET":
        return redirect("dashboard:login")

    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(username=username,password=password)
    login(request,user)
    return redirect("dashboard:user")

def logout_view(request):
    logout(request)
    return redirect("dashboard:login")

def index(request):
    randomID = random.randint(1,101)
    a = Order_sku(shopId=randomID,sku = 'qfawe' )

    a.save()
    return HttpResponse("<p>test</p>")

@login_required(login_url='dashboard:login')
def order(request):

    user = request.user.username
    user = User_assignment.objects.filter(user__username=user)
    dbr = user[0].distributor

    summary = Order_summary.objects.filter(retailer__distributor=dbr).values('date').annotate(shop_number = Count('retailer'),quantity_total = Sum('quantity_sum')).order_by('date')
    display_length = min(3,len(summary))
    summary = summary[0:display_length]
    #summary = Order_summary.objects.get(pk=1)
    return render(request, 'order.html',{'summary':summary})

@login_required(login_url='dashboard:login')
def order_add(request):
    return render(request, 'order_add.html')

@login_required(login_url='dashboard:login')
def order_submit(request):


        if request.method == "GET":
            return redirect("dashboard:order")

        date = request.POST['date']


        user = request.user.username
        user = User_assignment.objects.filter(user__username=user)
        dbr = user[0].distributor


        try:

            csv_file = request.FILES["csv_file"]
            line = csv_file.readlines()
            i = 0
            index = -1
            for row in line:
                s = str(row)
                s = s[2:(s.find("\\")-len(s))]
                d = s.split(",")
                if i==0:
                    i=1
                    try:
                        retail_index = d.index('shopId')
                        order_id_index = d.index('orderId')
                        item_index = d.index('itemId')
                        quantity_index = d.index('quantity')
                    except:
                        raise Http404("Some Fields are Missing!")
                else:
                    retailId = d[retail_index]
                    orderId = d[order_id_index]
                    itemId = d[item_index]
                    quantity = d[quantity_index]

                    rtl = Retailer.objects.get(distributor = dbr, shop_id = retailId)
                    item = Item.objects.get(distributor = dbr, item_id = itemId)
                    orderItem = Order_item(retailer = rtl, order_id = orderId, date = date, item = item, quantity = quantity)
                    orderItem.save()

            qry = Order_item.objects.values('retailer','order_id','date','retailer__latitude','retailer__longitude').annotate(qty_sum = Sum('quantity'),vol_sum = Sum(F('quantity')*F('item__volume'),output_field=FloatField()),weight_sum = Sum(F('quantity')*F('item__weight'),output_field=FloatField()))

            for result in qry:
                order_summary = Order_summary()
                order_summary.retailer = Retailer.objects.get(pk = result['retailer'])
                order_summary.order_id = result['order_id']
                order_summary.date = result['date']
                order_summary.quantity_sum = result['qty_sum']
                order_summary.weight_sum = result['weight_sum']
                order_summary.vol_sum =  result['vol_sum']
                order_summary.latitude = result['retailer__latitude']
                order_summary.longitude = result['retailer__longitude']
                order_summary.save()





            return HttpResponse("<p>asdf</p>")

        except Exception as e:
            return HttpResponse("<p>"+str(e)+"</p>")


@login_required(login_url='dashboard:login')
def shop(request):

        user = request.user.username
        user = User_assignment.objects.filter(user__username=user)
        dbr = user[0].distributor

        retailer_list = Retailer.objects.filter(distributor=dbr)

        paginator = Paginator(retailer_list, 1) # Show 25 contacts per page

        page = request.GET.get('page')
        retailer = paginator.get_page(page)

        return render(request, 'shop.html', {'retailer': retailer})


@login_required(login_url='dashboard:login')
def shop_add(request):
    return render(request, 'shop_add.html')

@login_required(login_url='dashboard:login')
def shop_search(request):
    shop_id = request.POST['shop_id']
    retail = Retailer.objects.get(shop_id=shop_id)
    pk = retail.pk
    return redirect("./shop_detail/"+str(pk))

@login_required(login_url='dashboard:login')
def shop_submit(request):

    if request.method == "GET":
        return redirect("dashboard:shop")

    else:
        user = request.user.username
        user = User_assignment.objects.filter(user__username=user)
        dbr = user[0].distributor

        submit_type = request.POST['submit_type']
        if submit_type!="0": #fill form

            shop_id = request.POST['shop_id']
            name = request.POST['shop_name']
            number = request.POST['number']
            address1 = request.POST['address1']
            address2 = request.POST['address2']
            city = request.POST['city']
            state = request.POST['state']
            latitude = request.POST['latitude']
            longitude = request.POST['longitude']

            if submit_type=="1":
                retailer = Retailer(shop_id=shop_id, distributor=dbr, name=name, number=number, address1=address1, address2=address2,city=city,state=state, latitude=latitude, longitude=longitude)
                retailer.save()
            else:
                Retailer.objects.filter(pk = request.POST['pk']).update(shop_id=shop_id, distributor=dbr, name=name, number=number, address1=address1, address2=address2,city=city,state=state, latitude=latitude, longitude=longitude)
                return redirect("./shop_detail/"+str(request.POST['pk']))
        else:

            try:

                csv_file = request.FILES["csv_file"]
                line = csv_file.readlines()
                i = 0
                index = -1
                for row in line:
                    s = str(row)
                    s = s[2:(s.find("\\")-len(s))]
                    d = s.split(",")
                    if i==0:
                        i=1
                        try:

                            shop_id_index = d.index('shopId')
                            name_index = d.index('name')
                            number_index = d.index('number')
                            address1_index = d.index('address1')
                            address2_index = d.index('address2')
                            city_index = d.index('city')
                            state_index = d.index('state')
                            latitude_index = d.index('latitude')
                            longitude_index = d.index('longitude')

                        except:
                            raise Http404("Some Fields are Missing!")
                    else:
                        shop_id =d[shop_id_index]
                        name = d[name_index]
                        number = d[number_index]
                        address1 = d[address1_index]
                        address2 = d[address2_index]
                        city = d[city_index]

dashboard/templates/distributor_edit.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Light Bootstrap Dashboard by Creative Tim</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


		{% load staticfiles %}

    <!-- Bootstrap core CSS     -->
    <link href=" {% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static 'assets/css/animate.min.css' %}" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{% static 'assets/css/light-bootstrap-dashboard.css?v=1.4.0' %}" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'assets/css/demo.css' %}" rel="stylesheet" />
		<link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
		<script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
    <link href="{% static 'assets/css/pe-icon-7-stroke.css' %}" rel="stylesheet" />
</head>
<body>

<div class="wrapper">
    <div class="sidebar" data-color="purple" data-image="{% static 'assets/img/sidebar-5.jpg' %}">

    <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->


    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="http://www.creative-tim.com" class="simple-text">
                    Creative Tim
                </a>
            </div>

            <ul class="nav">
                <li class="active">
                    <a href="{% url 'dashboard:user' %}">
                        <i class="pe-7s-user"></i>
                        <p>Profile</p>
                    </a>
                </li>
								<li>
                    <a href="{% url 'dashboard:resource' %}">
                        <i class="pe-7s-network"></i>
                        <p>Resource</p>
                    </a>
                </li>
								<li>
										<a href="{% url 'dashboard:item' %}">
												<i class="pe-7s-box1"></i>
												<p>Product Item</p>
										</a>
								</li>
                <li>
                    <a href="{% url 'dashboard:shop' %}">
                        <i class="pe-7s-shopbag"></i>
                        <p>Shop</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'dashboard:order' %}">
                        <i class="pe-7s-note2"></i>
                        <p>Order</p>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="pe-7s-map"></i>
                        <p>Route</p>
                    </a>
                </li>

            </ul>
    	</div>
    </div>

    <div class="main-panel">
		<nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>
                <div class="collapse navbar-collapse">


                    <ul class="nav navbar-nav navbar-right">
                        <li>
                           <a href="">
                               <p>Account</p>
                            </a>
                        </li>
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
										Dropdown
										<b class="caret"></b>
									</p>

                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                              </ul>
                        </li>
                        <li>
                            <a href="#">
                                <p>Log out</p>
                            </a>
                        </li>
						<li class="separator hidden-lg hidden-md"></li>
                    </ul>
                </div>
            </div>
        </nav>



				<div class="content">

				<div class="container-fluid">

					<div class="row">
							<div class="col-md-12">
									<div class="card">
											<div class="header">
													<h4 class="title">My Profile</h4>
											</div>
											<div class="content">
												<form action="{% url 'dashboard:user_submit' %}" method="post" enctype="multipart/form-data">
														{% csrf_token %}
															<div class="row">
																	<div class="col-md-6">
																			<div class="form-group">
																					<label>Name</label>
																					<input type="text" class="form-control" name ="dist_name" value="{{distributor.name}}">
																			</div>
																	</div>

																	<div class="col-md-6">
																			<div class="form-group">
																					<label for="exampleInputEmail1">Contact Number</label>
																					<input type="text" class="form-control" name="number" value="{{distributor.number}}">
																			</div>
																	</div>
															</div>


															<div class="row">
																	<div class="col-md-12">
																			<div class="form-group">
																					<label>Address 1</label>
																					<input type="text" class="form-control"  name = "address1" value="{{distributor.address1}}">
																			</div>
																	</div>
															</div>

															<div class="row">
																	<div class="col-md-12">
																			<div class="form-group">
																					<label>Address 2</label>
																					<input type="text" class="form-control"  name="address2" value="{{distributor.address2}}">
																			</div>
																	</div>
															</div>

															<div class="row">
																	<div class="col-md-4">
																			<div class="form-group">
																					<label>City</label>
																					<input type="text" class="form-control" name="city" value="{{distributor.city}}">
																			</div>
																	</div>
																	<div class="col-md-4">
																			<div class="form-group">
																					<label>State</label>
																					<input type="text" class="form-control" name="state" value="{{distributor.state}}">
																			</div>
																	</div>
																	<div class="col-md-4">
																			<div class="form-group">
																					<label>Postal Code</label>
																					<input type="text" class="form-control" name="zip_code">
																			</div>
																	</div>
															</div>


															<input type="hidden" value="2" name="submit_type" />
															<input type="hidden" value={{distributor.pk}} name="pk" />
															<button type="submit" class="btn btn-info btn-fill pull-right">Update</button>
															<div class="clearfix"></div>
													</form>
											</div>
									</div>
							</div>


					</div>













				</div>



				</div>







        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="#">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Company
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Portfolio
                            </a>
                        </li>
                        <li>
                            <a href="#">
                               Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <p class="copyright pull-right">
                    &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                </p>
            </div>
        </footer>


    </div>
</div>


</body>

    <!--   Core JS Files   -->
    <script src="{% static 'assets/js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>


	<link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel = "stylesheet">
		<script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
		<script>

			 $(function() {

					$( "#datepicker-order" ).datepicker({ dateFormat: 'yy-mm-dd' })
			 });



		</script>


	<!--  Charts Plugin -->
	<script src="{% static 'assets/js/chartist.min.js' %}"></script>

    <!--  Notifications Plugin    -->
    <script src="{% static 'assets/js/bootstrap-notify.js' %}"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="{% static 'assets/js/light-bootstrap-dashboard.js?v=1.4.0' %}"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="{% static 'assets/js/demo.js' %}"></script>


</html>

dashboard/templates/login.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Light Bootstrap Dashboard by Creative Tim</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


		{% load staticfiles %}

    <!-- Bootstrap core CSS     -->
    <link href=" {% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static 'assets/css/animate.min.css' %}" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{% static 'assets/css/light-bootstrap-dashboard.css?v=1.4.0' %}" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'assets/css/demo.css' %}" rel="stylesheet" />
		<link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
		<script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
    <link href="{% static 'assets/css/pe-icon-7-stroke.css' %}" rel="stylesheet" />
</head>
<body>









				<div class="content">

					<div class="row">
						<div class="col-md-3"></div>
					<div class="col-md-6">
					<div class="row">
							<div class="col-md-12">
									<div class="card">
											<div class="header">
													<h4 class="title">Create Account</h4>
											</div>
											<div class="content">
												<form action="{% url 'dashboard:login_submit' %}" method="post" enctype="multipart/form-data">
														{% csrf_token %}
															<div class="row">

																	<div class="col-md-6">
																			<div class="form-group">
																					<label>Username</label>
																					<input type="text" class="form-control" name="username">
																			</div>
																	</div>
																	<div class="col-md-6">
																			<div class="form-group">
																					<label>Password</label>
																					<input type="password" class="form-control" name="password">
																			</div>
																	</div>

															</div>



															<button type="submit" class="btn btn-info btn-fill pull-right">Login</button>
															<div class="clearfix"></div>
													</form>
											</div>
									</div>
							</div>


					</div>
				</div>
					<div class="col-md-3"></div>




















</div>


</body>

    <!--   Core JS Files   -->
    <script src="{% static 'assets/js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>


	<link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel = "stylesheet">
		<script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
		<script>

			 $(function() {

					$( "#datepicker-order" ).datepicker({ dateFormat: 'yy-mm-dd' })
			 });



		</script>


	<!--  Charts Plugin -->
	<script src="{% static 'assets/js/chartist.min.js' %}"></script>

    <!--  Notifications Plugin    -->
    <script src="{% static 'assets/js/bootstrap-notify.js' %}"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="{% static 'assets/js/light-bootstrap-dashboard.js?v=1.4.0' %}"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="{% static 'assets/js/demo.js' %}"></script>


</html>